spring:
  application:
    name: gateway-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/

zuul:
  routes:
    product-service:
      path: '/product/**'
      serviceId: product-service
  ignored-services: '*'

# expose all actuator endpoints
management.endpoints.web.exposure.include: '*'

