spring:
  application:
    name: gateway-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceurl:
    defaultzone: http://localhost:8761/eureka/